const localisation = {
  common: {
    loginTitle: {
      fr: 'Connectez-vous à un évènement',
      nl: '',
      de: '',
      en: '',
    },
    email: {
      fr: 'Adresse email',
      nl: '',
      de: '',
      en: '',
    },
    names: {
      fr: 'Nom, Prénom',
      nl: '',
      de: '',
      en: '',
    },
    password: {
      fr: 'Mot de passe',
      nl: '',
      de: '',
      en: '',
    },
    signin: {
      fr: 'Se connecter',
      nl: '',
      de: '',
      en: '',
    },
    signout: {
      fr: 'Déconnexion',
      nl: '',
      de: '',
      en: '',
    },
    delete: {
      fr: 'Supprimer',
      nl: '',
      de: '',
      en: '',
    },
    back: {
      fr: 'Retour',
      nl: '',
      de: '',
      en: '',
    },
    eventManagement: {
      fr: "Gestion de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    registerPage: {
      fr: "Page d'inscription publique",
      nl: '',
      de: '',
      en: '',
    },
    registerToEvent: {
      fr: "Inscription à l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    checkRegisterPage: {
      fr: "Consulter la page d'incription publique",
      nl: '',
      de: '',
      en: '',
    },
    listingPage: {
      fr: "Liste d'inscriptions publique",
      nl: '',
      de: '',
      en: '',
    },
    checkListingPage: {
      fr: 'Consulter la page contenant la liste des inscriptions',
      nl: '',
      de: '',
      en: '',
    },
    eventBacklinkText: {
      fr: "Texte de retour vers la page d'accueil",
      nl: '',
      de: '',
      en: '',
    },
    eventIsFree: {
      fr: "L'évènement est gratuit",
      nl: '',
      de: '',
      en: '',
    },
    showIsMotorized: {
      fr: "Donner la possibilité d'indiquer si l'on possède un véhicule pour se déplacer",
      nl: '',
      de: '',
      en: '',
    },
    showIsReserve: {
      fr: "Donner la possibilité d'indiquer si l'on souhaite être réserviste",
      nl: '',
      de: '',
      en: '',
    },
    showFideid: {
      fr: "Donner la possibilité de renseigner un matricule FIDE",
      nl: '',
      de: '',
      en: '',
    },
    registerShowDates: {
      fr: "Donner la possibilité de renseigner les disponibilités aux dates de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    registerShowDatesTooltip: {
      fr: "Vos disponibilités pour l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventHasGodfather: {
      fr: 'Donner la possibilité de renseigner un parrain',
      nl: '',
      de: '',
      en: '',
    },
    eventGodfatherInfoLink: {
      fr: "URL d'explication du parrainage",
      nl: '',
      de: '',
      en: '',
    },
    slugExistError: {
      fr: "L'identifiant de l'évènement exisite déjà. Choisissez-en un autre.",
      nl: '',
      de: '',
      en: '',
    },
    loginError: {
      fr: "L'adresse email et le mot de passe que vous avez introduit ne correspondent à aucun évènement.",
      nl: '',
      de: '',
      en: '',
    },
    eventConfig: {
      fr: "Configuration de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    general: {
      fr: 'Général',
      nl: '',
      de: '',
      en: '',
    },
    dates: {
      fr: 'Dates',
      nl: '',
      de: '',
      en: '',
    },
    date: {
      fr: 'Date',
      nl: '',
      de: '',
      en: '',
    },
    people: {
      fr: 'Personnes',
      nl: '',
      de: '',
      en: '',
    },
    eventName: {
      fr: "Nom de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventTitle: {
      fr: "Nom complet de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventSlug: {
      fr: "Identifiant de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventLogo: {
      fr: "URL du logo de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventIcon: {
      fr: "URL de l'icône de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    eventHomepage: {
      fr: "URL de la page d'accueil de l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    title: {
      fr: 'Titre',
      nl: '',
      de: '',
      en: '',
    },
    alias: {
      fr: 'Alias',
      nl: '',
      de: '',
      en: '',
    },
    phone: {
      fr: 'Numéro de téléphone',
      nl: '',
      de: '',
      en: '',
    },
    phoneShort: {
      fr: 'Téléphone',
      nl: '',
      de: '',
      en: '',
    },
    nationality: {
      fr: 'Nationalité',
      nl: '',
      de: '',
      en: '',
    },
    godfather: {
      fr: 'Parrain',
      nl: '',
      de: '',
      en: '',
    },
    godfatherFromUser: {
      fr: "Parrain renseigné par la personne à l'enregistrement",
      nl: '',
      de: '',
      en: '',
    },
    optional: {
      fr: 'facultatif',
      nl: '',
      de: '',
      en: '',
    },
    save: {
      fr: 'Enregistrer',
      nl: '',
      de: '',
      en: '',
    },
    knowmore: {
      fr: 'En savoir plus',
      nl: '',
      de: '',
      en: '',
    },
    notes: {
      fr: 'Remarques',
      nl: '',
      de: '',
      en: '',
    },
    notesFromUser: {
      fr: "Remarques de la personne à l'enregistrement",
      nl: '',
      de: '',
      en: '',
    },
    moreInfo: {
      fr: 'Consultez toutes les informations sur cette personne.',
      nl: '',
      de: '',
      en: '',
    },
    clickToUpdateTooltip: {
      fr: "\nCliquez ici pour mettre à jour l'information.",
      nl: '',
      de: '',
      en: '',
    },
    isMotorizedSelfTooltip: {
      fr: "Je possède un véhicule pour me déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isNotMotorizedSelfTooltip: {
      fr: "Je ne possède pas de véhicule pour me déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isMotorizedUnknowSelfTooltip: {
      fr: "Je ne sais pas encore si je possède un véhicule pour me déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isMotorizedTooltip: {
      fr: "Cette personne possède un véhicule pour se déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isNotMotorizedTooltip: {
      fr: "Cette personne ne possède pas de véhicule pour se déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isMotorizedUnknowTooltip: {
      fr: "Cette personne ne sait pas encore si elle possède un véhicule pour se déplacer à l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isReserveSelfTooltip: {
      fr: 'Je souhaite être réserviste.',
      nl: '',
      de: '',
      en: '',
    },
    isNotReserveSelfTooltip: {
      fr: 'Je souhaite être titulaire.',
      nl: '',
      de: '',
      en: '',
    },
    isReserveUnknowSelfTooltip: {
      fr: 'Je ne sais pas encore si je souhaite être titulaire ou réserviste.',
      nl: '',
      de: '',
      en: '',
    },
    isReserveTooltip: {
      fr: 'Cette personne souhaite être réserviste.',
      nl: '',
      de: '',
      en: '',
    },
    isNotReserveTooltip: {
      fr: 'Cette personne souhaite être titulaire.',
      nl: '',
      de: '',
      en: '',
    },
    isReserveUnknowTooltip: {
      fr: "Ce joueur ne sait pas encore s'il souhaite être titulaire ou réserviste.",
      nl: '',
      de: '',
      en: '',
    },
    registerTo: {
      fr: "S'inscrire à l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    summary: {
      fr: 'Récapitulatif',
      nl: '',
      de: '',
      en: '',
    },
    availables: {
      fr: 'Disponibles',
      nl: '',
      de: '',
      en: '',
    },
    notAvailables: {
      fr: 'Indisponibles',
      nl: '',
      de: '',
      en: '',
    },
    unknowns: {
      fr: 'Décisions inconnues',
      nl: '',
      de: '',
      en: '',
    },
    fideid: {
      fr: 'Matricule FIDE',
      nl: '',
      de: '',
      en: '',
    },
    elo: {
      fr: 'Classement Elo',
      nl: '',
      de: '',
      en: '',
    },
    paymentNote: {
      fr: 'Note sur le paiement',
      nl: '',
      de: '',
      en: '',
    },
    backToTheEvent: {
      fr: "Retour à l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    sortUsersByName: {
      fr: 'Trier par ordre alphabétique',
      nl: '',
      de: '',
      en: '',
    },
    areyousure: {
      fr: 'Êtes-vous sûr(e) ?',
      nl: '',
      de: '',
      en: '',
    },
    createUser: {
      fr: 'Ajouter une personne',
      nl: '',
      de: '',
      en: '',
    },
    tableView: {
      fr: 'Vue en tableau',
      nl: '',
      de: '',
      en: '',
    },
    classicView: {
      fr: 'Vue en liste',
      nl: '',
      de: '',
      en: '',
    },
    createDate: {
      fr: 'Ajouter une date',
      nl: '',
      de: '',
      en: '',
    },
    updateEmail: {
      fr: "Mettre à jour l'adresse email",
      nl: '',
      de: '',
      en: '',
    },
    sendPassword: {
      fr: 'Envoyer le mot de passe par email',
      nl: '',
      de: '',
      en: '',
    },
    sendPasswordConfirm: {
      fr: 'Voulez-vous envoyer le mot de passe par email ?',
      nl: '',
      de: '',
      en: '',
    },
    passwordSent: {
      fr: 'Le mot de passe a été envoyé par email.\nCliquez ici pour le renvoyer par email à la personne.',
      nl: '',
      de: '',
      en: '',
    },
    passwordNotSent: {
      fr: "Le mot de passe n'a pas encore été envoyé.\nCliquez ici pour l'envoyer par email à la personne.",
      nl: '',
      de: '',
      en: '',
    },
    isHiddenTooltip: {
      fr: 'Cet utilisateur est invisible dans la liste.\nCliquez ici pour le rendre visible.',
      nl: '',
      de: '',
      en: '',
    },
    isVisibleTooltip: {
      fr: 'Cet utilisateur est visible dans la liste.\nCliquez ici pour le rendre invisible.',
      nl: '',
      de: '',
      en: '',
    },
    isValidatedSimpleTooltip: {
      fr: 'Cet utilisateur est validé.',
      nl: '',
      de: '',
      en: '',
    },
    isValidatedTooltip: {
      fr: 'Cet utilisateur est validé.\nCliquez ici pour changer le statut en "non validé".',
      nl: '',
      de: '',
      en: '',
    },
    isNotValidatedTooltip: {
      fr: 'Cet utilisateur n\'est pas validé.\nCliquez ici pour changer le statut en "validé".',
      nl: '',
      de: '',
      en: '',
    },
    hasPaidSimpleTooltip: {
      fr: 'Cet utilisateur a payé.',
      nl: '',
      de: '',
      en: '',
    },
    hasPaidTooltip: {
      fr: 'Cet utilisateur a payé.\nCliquez ici pour changer le statut en "non payé".',
      nl: '',
      de: '',
      en: '',
    },
    hasNotPaidTooltip: {
      fr: 'Cet utilisateur n\'a pas encore payé.\nCliquez ici pour changer le statut en "payé".',
      nl: '',
      de: '',
      en: '',
    },
    isLockedTooltip: {
      fr: 'Cette date est verrouillée.\nCliquez ici pour la déverrouiller.',
      nl: '',
      de: '',
      en: '',
    },
    isNotLockedTooltip: {
      fr: 'Cette date est déverrouillée.\nCliquez ici pour la verrouiller.',
      nl: '',
      de: '',
      en: '',
    },
    isOwnerSimpleTooltip: {
      fr: "Cet utilisateur est administrateur de l'évènement.",
      nl: '',
      de: '',
      en: '',
    },
    isOwnerTooltip: {
      fr: "Cet utilisateur est administrateur de l'évènement.\nCliquez ici pour lui retirer ses droits.",
      nl: '',
      de: '',
      en: '',
    },
    isNotOwnerTooltip: {
      fr: "Cet utilisateur n'est pas administrateur de l'évènement.\nCliquez ici pour lui donner les droits.",
      nl: '',
      de: '',
      en: '',
    },
    errorEmailExist: {
      fr: "L'adresse email que vous avez introduite a déjà été utilisée pour cet évènement.",
      nl: '',
      de: '',
      en: '',
    },
    errorMessage: {
      fr: 'Une erreur est survenue.',
      nl: '',
      de: '',
      en: '',
    },
    successRegister: {
      fr: 'Merci, vous avez bien été inscrit(e) à l\'évènement',
      nl: '',
      de: '',
      en: '',
    },
    registerAnotherPerson: {
      fr: 'Inscrire une autre personne à l\'évènement',
      nl: '',
      de: '',
      en: '',
    },
    validated: {
      fr: 'Validé',
      nl: '',
      de: '',
      en: '',
    },
    paid: {
      fr: 'Payé',
      nl: '',
      de: '',
      en: '',
    },
    hidden: {
      fr: 'Masqué',
      nl: '',
      de: '',
      en: '',
    },
    owner: {
      fr: 'Admin',
      nl: '',
      de: '',
      en: '',
    },
    motorized: {
      fr: 'Véhiculé',
      nl: '',
      de: '',
      en: '',
    },
    reserve: {
      fr: 'Réserviste',
      nl: '',
      de: '',
      en: '',
    },
    passwordSentShort: {
      fr: 'MDP',
      nl: '',
      de: '',
      en: '',
    },
    savePeoplePosition: {
      fr: 'Sauvegarder la position des personnes',
      nl: '',
      de: '',
      en: '',
    },
  },
  emailText: {
    sendPasswordTitle: {
      fr: "Votre mot de passe pour l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    sendPasswordContent: {
      fr: "Voici vos informations de connexion afin de donner vos disponibilités pour l'évènement",
      nl: '',
      de: '',
      en: '',
    },
    sendPasswordHello: {
      fr: 'Bonjour',
      nl: '',
      de: '',
      en: '',
    },
    sendPasswordSeeyousoon: {
      fr: 'À bientôt',
      nl: '',
      de: '',
      en: '',
    },
    sendPasswordClickhere: {
      fr: "Cliquez ici pour accèder à l'èvenement",
      nl: '',
      de: '',
      en: '',
    },
    newRegisterInfo: {
      fr: "Une nouvelle personne s'est enregistrée à l'évènement",
      nl: '',
      de: '',
      en: '',
    },
  },
}

export const getLocal = (hierarchy: Array<string>) => {
  // const loggedUser: User = useState<User>('loggedUser').value
  const chosenLanguage: string = 'fr'
  let target: any = localisation

  try {
    for (let item of hierarchy) {
      target = target[item]
    }

    return target[chosenLanguage]
  } catch (e) {
    return hierarchy[hierarchy.length - 1]
  }
}
